name: formality
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10.16
  - pip=24.3
  - torchvision=0.15.2
  - pytorch-cuda=12.1
  - pytorch=2.3.0
  - pip:
      - transformers==4.48.3
      - datasets==3.3.0
      - scikit-learn=1.6.1